### ISSUE TITLE
Bad certificate chain gives unhelpful error

### ISSUE THREAD

**Issue by anacrolix** [flok99/httping#10]
Pinging a host that serves up a cert for another host:

> Auto enabling SSL due to https-URLPING X:443 (/):
> short read during receiving reply-headers from host

Curl gives the more helpful:

> curl: (60) SSL certificate problem: Invalid certificate chain

**Comment by flok99** [comment]
Looking forward to your patches.


regards

On Sat, Mar 12, 2016 at 2:07 PM, Matt Joiner <notifications@github.com>
wrote:

> Pinging a host that serves up a cert for another host:
>
> Auto enabling SSL due to https-URLPING rnla2:443 (/):
> short read during receiving reply-headers from host
>
> Curl gives the more helpful:
>
> curl: (60) SSL certificate problem: Invalid certificate chain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/httping/issues/10>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment]
Can you give me an url to test this?

**Comment by flok99** [comment]
fixed in current version
