### ISSUE TITLE
Reuse HTTP connection

### ISSUE THREAD

**Issue by noway421** [flok99/httping#14]
Right now each HEAD request is sent in a new TCP connection. But if the server does not send Connection: close, it would be useful to have the option to reuse the same connection.

**Comment by flok99** [comment]
Did you try -Q?

On Thu, Jul 7, 2016 at 2:42 AM, Way, No <notifications@github.com> wrote:

> Right now each HEAD request is sent in a new TCP connection. But if the
> server does not send Connection: close, it would be useful to have the
> option to reuse the same connection.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/flok99/httping/issues/14>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADESuEhL5OLX11gkR_rl6G0PmvFpInQ4ks5qTGeAgaJpZM4JGr_8>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by noway421** [comment]
Ohh, okay. In the #15 there are some changes for clarification.
