### ISSUE TITLE
Compiling on CentOS7... also requires gettext

### ISSUE THREAD

**Issue by ryanerwin** [flok99/httping#22]
Running `./configure`, httping just outputs that:

```
- this system does NOT have the ncurses development libraries - they are optional
- this system does NOT have the OpenSSL development libraries - they are optional
- this system does NOT have the FFTW3 development libraries - they are optional and only useful when also including ncurses
```

But there doesn't seem to be a check for **gettext** and **gettext-devel**. Also, the "-O" option seems to be required under OFLAGS.

I installed the following:
```
yum install ncurses-devel fftw-devel openssl-devel gettext gettext-devel
```
Unless you install gettext, the build will fail due to: `make: msgfmt: Command not found`.

After you run `./configure`, you'll need to modify the `Makefile` and change **OFLAGS**:
```
OFLAGS=-O
```
After this, httping should build/compile/install just fine.

**Comment by flok99** [comment]
Meh. Someone should rewrite the configure script into a cmake (preferred) or autoconf version.
