### ISSUE TITLE
autoconf / cmake

### ISSUE THREAD

**Issue by flok99** [flok99/httping#3]
Someone should step up and create autoconf or cmake scripts for httping.

**Comment by OlafvdSpek** [comment]
Why?

**Comment by flok99** [comment]
It should make compiling on a different platform than linux on a pc more
easy.

On Sat, Jun 27, 2015 at 12:38 AM, Olaf van der Spek <
notifications@github.com> wrote:

> Why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/httping/issues/3#issuecomment-115909696>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
