### ISSUE TITLE
Missing \n ?

### ISSUE THREAD

**Issue by OlafvdSpek** [flok99/httping#5]
A \n appears to be missing between URL and PING..

Is the enabling SSL note useful at all?

$ httping https://xwis.net
Auto enabling SSL due to https-URLPING xwis.net:443 (/):
connected to 46.105.123.98:443 (238 bytes), seq=0 time=172.92 ms

**Comment by flok99** [comment]
fixed

**Comment by flok99** [comment]
On Sat, Jun 27, 2015 at 12:39 AM, Olaf van der Spek <
notifications@github.com> wrote:

> due to https-URL


ok fixed


-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
