### ISSUE TITLE
Stuck @ short read during receiving reply-headers from host?

### ISSUE THREAD

**Issue by OlafvdSpek** [flok99/httping#6]
$ httping -V
HTTPing v2.3.4, (C) 2003-2013 folkert@vanheusden.com
 * SSL support included (-l)
 * ncurses interface with FFT included (-K)

$ httping -l https://connect.microsoft.com/VisualStudio/feedback/details/634583/include-completion-uses-back-instead-of-forward-slashes
PING connect.microsoft.com:443 (/VisualStudio/feedback/details/634583/include-completion-uses-back-instead-of-forward-slashes):
short read during receiving reply-headers from host

strace shows httping looping over this:
ioctl(3, SNDRV_TIMER_IOCTL_INFO or TIOCOUTQ, [229]) = 0
gettimeofday({1435358883, 706534}, {0, 0}) = 0
nanosleep({0, 500000}, NULL)            = 0

**Comment by flok99** [comment]
Hi,

Please consider upgrading the debian package of httping to the latest (2.4,
http://www.vanheusden.com/httping/httping-2.4.tgz ) version.

Thanks.

On Sat, Jun 27, 2015 at 12:49 AM, Olaf van der Spek <
notifications@github.com> wrote:

> httping -l
> https://connect.microsoft.com/VisualStudio/feedback/details/634583/include-completion-uses-back-instead-of-forward-slashes
>




-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by OlafvdSpek** [comment]
Oops, thought I was current already..
