### ISSUE TITLE
2.6 does not compile under Cygwin (gcc 4.9.3)

### ISSUE THREAD

**Issue by jaalto** [flok99/httping#7]
Build log attached.

**\* HTTPing v2.4 () configure script ***
- this system does NOT support TCP fast open - this is an optional feature
- this system does NOT have the ncurses development libraries - they are optional
- this system does NOT have the OpenSSL development libraries - they are optional
- this system does NOT have the FFTW3 development libraries - they are optional and only useful when also including ncurses

gcc (GCC) 4.9.3
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o gen.o gen.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o http.o http.c
http.c: In function 'get_HTTP_headers':
http.c:22:2: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
  char _buffer = (char *)malloc(len + 1);
  ^
http.c:22:25: warning: incompatible implicit declaration of built-in function 'malloc'
  char *buffer = (char *)malloc(len + 1);
                         ^
http.c:48:4: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
    free(buffer);
    ^
http.c:48:4: warning: incompatible implicit declaration of built-in function 'free'
http.c:65:4: warning: implicit declaration of function 'realloc' [-Wimplicit-function-declaration]
    buffer = (char *)realloc(buffer, len + 1);
    ^
http.c:65:21: warning: incompatible implicit declaration of built-in function 'realloc'
    buffer = (char *)realloc(buffer, len + 1);
                     ^
http.c:18:41: warning: unused parameter 'ssl_h' [-Wunused-parameter]
 int get_HTTP_headers(int socket_h, SSL *ssl_h, char *_headers, int _overflow, double timeout)
                                         ^
http.c: In function 'dumb_get_HTTP_headers':
http.c:83:25: warning: incompatible implicit declaration of built-in function 'malloc'
  char *buffer = (char *)malloc(len);
                         ^
http.c:98:4: warning: incompatible implicit declaration of built-in function 'free'
    free(buffer);
    ^
http.c:113:21: warning: incompatible implicit declaration of built-in function 'realloc'
    buffer = (char *)realloc(buffer, len);
                     ^
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o io.o io.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o error.o error.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o utils.o utils.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o main.o main.c
main.c: In function 'handler_quit':
main.c:67:23: warning: unused parameter 's' [-Wunused-parameter]
 void handler_quit(int s)
                       ^
main.c: At top level:
main.c:835:7: warning: ISO C90 does not support 'long long' [-Wlong-long]
  long long int Bps_avg;
       ^
main.c: In function 'main':
main.c:1592:8: warning: ISO C90 does not support 'long long' [-Wlong-long]
   long long int bytes_transferred = 0;
        ^
main.c:1826:26: error: 'TIOCOUTQ' undeclared (first use in this function)
     int i_rc = ioctl(fd, TIOCOUTQ, &bytes_left);
                          ^
main.c:1826:26: note: each undeclared identifier is reported only once for each function it appears in
main.c:1598:13: warning: unused variable 'recv_tos_len' [-Wunused-variable]
   socklen_t recv_tos_len = sizeof recv_tos;
             ^
main.c:2405:1: warning: label 'error_exit' defined but not used [-Wunused-label]
 error_exit:
 ^
main.c:934:9: warning: variable 'show_slow_log' set but not used [-Wunused-but-set-variable]
  double show_slow_log = MY_DOUBLE_INF;
         ^
main.c:932:7: warning: unused variable 'nc_graph' [-Wunused-variable]
  char nc_graph = 1;
       ^
main.c:931:9: warning: variable 'graph_limit' set but not used [-Wunused-but-set-variable]
  double graph_limit = MY_DOUBLE_INF;
         ^
main.c:930:7: warning: unused variable 'first_resolve' [-Wunused-variable]
  char first_resolve = 1;
       ^
main.c:909:7: warning: unused variable 's_bio' [-Wunused-variable]
  BIO *s_bio = NULL;
       ^
main.c:884:7: warning: variable 'wait_set' set but not used [-Wunused-but-set-variable]
  char wait_set = 0;
       ^
<builtin>: recipe for target 'main.o' failed
make: *_\* [main.o] Error 1

**Comment by jaalto** [comment]
This solves it partially. Please apply.

    --- a/Makefile
    +++ b/Makefile
    @@ -34,7 +34,7 @@ TARGET=httping
     LOCALEDIR=/usr/share/locale

     DEBUG=yes
    -WFLAGS=-Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2
    +WFLAGS=-std=gnu11 -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2
     OFLAGS=
     CFLAGS+=$(WFLAGS) $(OFLAGS) -DVERSION=\"$(VERSION)\" -DLOCALEDIR=\"$(LOCALEDIR)\"
     LDFLAGS+=-lm

**Comment by jaalto** [comment]
After -std=gnu11 these errors remain

*** HTTPing v2.4 () configure script ***

- this system does NOT support TCP fast open - this is an optional feature
- this system does NOT have the ncurses development libraries - they are optional
- this system does NOT have the OpenSSL development libraries - they are optional
- this system does NOT have the FFTW3 development libraries - they are optional and only useful when also including ncurses

gcc (GCC) 4.9.3
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o gen.o gen.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o http.o http.c
http.c: In function 'get_HTTP_headers':
http.c:22:2: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
  char *buffer = (char *)malloc(len + 1);
  ^
http.c:22:25: warning: incompatible implicit declaration of built-in function 'malloc'
  char *buffer = (char *)malloc(len + 1);
                         ^
http.c:48:4: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
    free(buffer);
    ^
http.c:48:4: warning: incompatible implicit declaration of built-in function 'free'
http.c:65:4: warning: implicit declaration of function 'realloc' [-Wimplicit-function-declaration]
    buffer = (char *)realloc(buffer, len + 1);
    ^
http.c:65:21: warning: incompatible implicit declaration of built-in function 'realloc'
    buffer = (char *)realloc(buffer, len + 1);
                     ^
http.c:18:41: warning: unused parameter 'ssl_h' [-Wunused-parameter]
 int get_HTTP_headers(int socket_h, SSL *ssl_h, char **headers, int *overflow, double timeout)
                                         ^
http.c: In function 'dumb_get_HTTP_headers':
http.c:83:25: warning: incompatible implicit declaration of built-in function 'malloc'
  char *buffer = (char *)malloc(len);
                         ^
http.c:98:4: warning: incompatible implicit declaration of built-in function 'free'
    free(buffer);
    ^
http.c:113:21: warning: incompatible implicit declaration of built-in function 'realloc'
    buffer = (char *)realloc(buffer, len);
                     ^
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o io.o io.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o error.o error.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o utils.o utils.c
gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o main.o main.c
main.c: In function 'handler_quit':
main.c:67:23: warning: unused parameter 's' [-Wunused-parameter]
 void handler_quit(int s)
                       ^
main.c: At top level:
main.c:835:7: warning: ISO C90 does not support 'long long' [-Wlong-long]
  long long int Bps_avg;
       ^
main.c: In function 'main':
main.c:1592:8: warning: ISO C90 does not support 'long long' [-Wlong-long]
   long long int bytes_transferred = 0;
        ^
main.c:1826:26: error: 'TIOCOUTQ' undeclared (first use in this function)
     int i_rc = ioctl(fd, TIOCOUTQ, &bytes_left);
                          ^
main.c:1826:26: note: each undeclared identifier is reported only once for each function it appears in
main.c:1598:13: warning: unused variable 'recv_tos_len' [-Wunused-variable]
   socklen_t recv_tos_len = sizeof recv_tos;
             ^
main.c:2405:1: warning: label 'error_exit' defined but not used [-Wunused-label]
 error_exit:
 ^
main.c:934:9: warning: variable 'show_slow_log' set but not used [-Wunused-but-set-variable]
  double show_slow_log = MY_DOUBLE_INF;
         ^
main.c:932:7: warning: unused variable 'nc_graph' [-Wunused-variable]
  char nc_graph = 1;
       ^
main.c:931:9: warning: variable 'graph_limit' set but not used [-Wunused-but-set-variable]
  double graph_limit = MY_DOUBLE_INF;
         ^
main.c:930:7: warning: unused variable 'first_resolve' [-Wunused-variable]
  char first_resolve = 1;
       ^
main.c:909:7: warning: unused variable 's_bio' [-Wunused-variable]
  BIO *s_bio = NULL;
       ^
main.c:884:7: warning: variable 'wait_set' set but not used [-Wunused-but-set-variable]
  char wait_set = 0;
       ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by flok99** [comment]
Hi,

Can you please try the current version? I made a fix a minute ago.

On Mon, Sep 28, 2015 at 6:57 AM, Jari Aalto <notifications@github.com>
wrote:

> Build log attached.
>
> *** HTTPing v2.4 () configure script ***
>
>    - this system does NOT support TCP fast open - this is an optional
>    feature
>    - this system does NOT have the ncurses development libraries - they
>    are optional
>    - this system does NOT have the OpenSSL development libraries - they
>    are optional
>    - this system does NOT have the FFTW3 development libraries - they are
>    optional and only useful when also including ncurses
>
> gcc (GCC) 4.9.3
> gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2 -DVERSION=\"2.4\"
> -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb -c -o gen.o gen.c
> gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2 -DVERSION=\"2.4\"
> -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb -c -o http.o
> http.c
> http.c: In function 'get_HTTP_headers':
> http.c:22:2: warning: implicit declaration of function 'malloc'
> [-Wimplicit-function-declaration]
> char
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *buffer = (char *)malloc(len + 1); ^ http.c:22:25: warning: incompatible
> implicit declaration of built-in function 'malloc' char *buffer = (char
> *)malloc(len + 1); ^ http.c:48:4: warning: implicit declaration of function
> 'free' [-Wimplicit-function-declaration] free(buffer); ^ http.c:48:4:
> warning: incompatible implicit declaration of built-in function 'free'
> http.c:65:4: warning: implicit declaration of function 'realloc'
> [-Wimplicit-function-declaration] buffer = (char *)realloc(buffer, len +
> 1); ^ http.c:65:21: warning: incompatible implicit declaration of built-in
> function 'realloc' buffer = (char *)realloc(buffer, len + 1); ^
> http.c:18:41: warning: unused parameter 'ssl_h' [-Wunused-parameter] int
> get_HTTP_headers(int socket_h, SSL *ssl_h, char **headers, int
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *overflow, double timeout) ^ http.c: In function 'dumb_get_HTTP_headers':
> http.c:83:25: warning: incompatible implicit declaration of built-in
> function 'malloc' char *buffer = (char *)malloc(len); ^ http.c:98:4:
> warning: incompatible implicit declaration of built-in function 'free'
> free(buffer); ^ http.c:113:21: warning: incompatible implicit declaration
> of built-in function 'realloc' buffer = (char *)realloc(buffer, len); ^ gcc
> -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2 -DVERSION=\"2.4\"
> -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb -c -o io.o io.c
> gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2 -DVERSION=\"2.4\"
> -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb -c -o error.o
> error.c gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2
> -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb
> -c -o utils.o utils.c gcc -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2
> -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb
> -c -o main.o main.c main.c: In function 'handler_quit': main.c:67:23:
> warning: unused parameter 's' [-Wunused-parameter] void handler_quit(int s)
> ^ main.c: At top level: main.c:835:7: warning: ISO C90 does not support
> 'long long' [-Wlong-long] long long int Bps_avg; ^ main.c: In function
> 'main': main.c:1592:8: warning: ISO C90 does not support 'long long'
> [-Wlong-long] long long int bytes_transferred = 0; ^ main.c:1826:26: error:
> 'TIOCOUTQ' undeclared (first use in this function) int i_rc = ioctl(fd,
> TIOCOUTQ, &bytes_left); ^ main.c:1826:26: note: each undeclared identifier
> is reported only once for each function it appears in main.c:1598:13:
> warning: unused variable 'recv_tos_len' [-Wunused-variable] socklen_t
> recv_tos_len = sizeof recv_tos; ^ main.c:2405:1: warning: label
> 'error_exit' defined but not used [-Wunused-label] error_exit: ^
> main.c:934:9: warning: variable 'show_slow_log' set but not used
> [-Wunused-but-set-variable] double show_slow_log = MY_DOUBLE_INF; ^
> main.c:932:7: warning: unused variable 'nc_graph' [-Wunused-variable] char
> nc_graph = 1; ^ main.c:931:9: warning: variable 'graph_limit' set but not
> used [-Wunused-but-set-variable] double graph_limit = MY_DOUBLE_INF; ^
> main.c:930:7: warning: unused variable 'first_resolve' [-Wunused-variable]
> char first_resolve = 1; ^ main.c:909:7: warning: unused variable 's_bio'
> [-Wunused-variable] BIO *s_bio = NULL; ^ main.c:884:7: warning: variable
> 'wait_set' set but not used [-Wunused-but-set-variable] char wait_set = 0;
> ^ : recipe for target 'main.o' failed make: *** [main.o] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/httping/issues/7>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by jaalto** [comment]
...Oh, copy-buffer didn't update when I pasted. Here is it

gcc (GCC) 4.9.3
gcc -std=gnu11 -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2  -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb   -c -o main.o main.c
main.c: In function 'handler_quit':
main.c:67:23: warning: unused parameter 's' [-Wunused-parameter]
 void handler_quit(int s)
                       ^
main.c: In function 'main':
main.c:1826:26: error: 'TIOCOUTQ' undeclared (first use in this function)
     int i_rc = ioctl(fd, TIOCOUTQ, &bytes_left);
                          ^
main.c:1826:26: note: each undeclared identifier is reported only once for each function it appears in
main.c:1598:13: warning: unused variable 'recv_tos_len' [-Wunused-variable]
   socklen_t recv_tos_len = sizeof recv_tos;
             ^
main.c:2405:1: warning: label 'error_exit' defined but not used [-Wunused-label]
 error_exit:
 ^
main.c:934:9: warning: variable 'show_slow_log' set but not used [-Wunused-but-set-variable]
  double show_slow_log = MY_DOUBLE_INF;
         ^
main.c:932:7: warning: unused variable 'nc_graph' [-Wunused-variable]
  char nc_graph = 1;
       ^
main.c:931:9: warning: variable 'graph_limit' set but not used [-Wunused-but-set-variable]
  double graph_limit = MY_DOUBLE_INF;
         ^
main.c:930:7: warning: unused variable 'first_resolve' [-Wunused-variable]
  char first_resolve = 1;
       ^
main.c:909:7: warning: unused variable 's_bio' [-Wunused-variable]
  BIO *s_bio = NULL;
       ^
main.c:884:7: warning: variable 'wait_set' set but not used [-Wunused-but-set-variable]
  char wait_set = 0;
       ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by flok99** [comment]
that's weird; it complains about the same code even though it is #ifndef'd
for cygwin.
are you sure you did a git pull -a?

On Mon, Sep 28, 2015 at 7:28 AM, Jari Aalto <notifications@github.com>
wrote:

> ...Oh, copy-buffer didn't update when I pasted. Here is it
>
> gcc (GCC) 4.9.3
> gcc -std=gnu11 -Wall -W -Wextra -pedantic -D_FORTIFY_SOURCE=2
> -DVERSION=\"2.4\" -DLOCALEDIR=\"/usr/share/locale\" -DNO_SSL -D_DEBUG -ggdb
> -c -o main.o main.c
> main.c: In function 'handler_quit':
> main.c:67:23: warning: unused parameter 's' [-Wunused-parameter]
> void handler_quit(int s)
> ^
> main.c: In function 'main':
> main.c:1826:26: error: 'TIOCOUTQ' undeclared (first use in this function)
> int i_rc = ioctl(fd, TIOCOUTQ, &bytes_left);
> ^
> main.c:1826:26: note: each undeclared identifier is reported only once for
> each function it appears in
> main.c:1598:13: warning: unused variable 'recv_tos_len' [-Wunused-variable]
> socklen_t recv_tos_len = sizeof recv_tos;
> ^
> main.c:2405:1: warning: label 'error_exit' defined but not used
> [-Wunused-label]
> error_exit:
> ^
> main.c:934:9: warning: variable 'show_slow_log' set but not used
> [-Wunused-but-set-variable]
> double show_slow_log = MY_DOUBLE_INF;
> ^
> main.c:932:7: warning: unused variable 'nc_graph' [-Wunused-variable]
> char nc_graph = 1;
> ^
> main.c:931:9: warning: variable 'graph_limit' set but not used
> [-Wunused-but-set-variable]
> double graph_limit = MY_DOUBLE_INF;
> ^
> main.c:930:7: warning: unused variable 'first_resolve' [-Wunused-variable]
> char first_resolve = 1;
> ^
> main.c:909:7: warning: unused variable 's_bio' [-Wunused-variable]
> BIO
>
>
>
>
>
> *s_bio = NULL; ^ main.c:884:7: warning: variable 'wait_set' set but not
> used [-Wunused-but-set-variable] char wait_set = 0; ^ : recipe for target
> 'main.o' failed make: *** [main.o] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/httping/issues/7#issuecomment-143659921>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by jaalto** [comment]
That was fromt he official. Release. Please pull this to latest Git https://github.com/flok99/httping/pull/8

**Comment by flok99** [comment]
Problem is fixed in the git version.
