### ISSUE TITLE
typo in io.c

### ISSUE THREAD

**Issue by tfarina** [flok99/httping#9]
https://github.com/flok99/httping/blob/master/io.c#L42

s/myread/read_to

**Comment by flok99** [comment]
Oh indeed!
Thanks!

On Wed, Oct 28, 2015 at 8:30 PM, Thiago Farina <notifications@github.com>
wrote:

> https://github.com/flok99/httping/blob/master/io.c#L42
>
> s/myread/read_to
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/httping/issues/9>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info
